runtime: python38 # or python37 for Python 3.7
service: freenit-backend

instance_class: F2

env_variables:
  BUCKET_NAME: "freenit"

handlers:
# Matches requests to /images/... to files in static/images/...
- url: /images
  static_dir: static/images

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
