runtime: python38 # or python37 for Python 3.7
service: freenit-backend

instance_class: F2

env_variables:
  BUCKET_NAME: "freenit"

handlers:
  - url: /.*
  - script: bin/init.sh
  - script: bin/uwsgi.sh

libraries:
  - name: freenit
  - name: flask
